[book]
authors = ["TimUntersberger"]
language = "en"
multilingual = false
src = "src"
title = "Nog Documentation"

[build]
build-dir = "../docs"

[preprocessor.index]

[output.html]
no-section-label = true
git-repository-url = "https://github.com/TimUntersberger/nog"
curly-quotes = true

[output.html.fold]
enable = true
level = 0
