[book]
title = "Nog Documentation"
authors = ["TimUntersberger"]
src = "src"

[build]
build-dir = "../docs"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/TimUntersberger/nog"

[output.html.fold]
enable = true
level = 0
