name: Auto Delete

on: [ delete ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: nelonoel/branch-name@v1
    - uses: actions/checkout@v2.3.1
    - name: Delete Release
      run: hub release delete '${{ env.BRANCH_NAME }}'
    - name: Delete Tag
      run: git push -d origin '${{ env.BRANCH_NAME }}-release'
