name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1.0.1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set Env
      run: |
        # disable command workflow processing
        echo "::stop-commands::pause-logging"
        echo "::set-env name=COMMIT_HASH::$(git rev-parse --short HEAD)"
        # enable command workflow processing
        echo "::pause-logging::"
    - name: Make Release
      run: ./bin/make_release.ps1 "${{ env.BRANCH_NAME }} ${{ env.COMMIT_HASH }}"
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.BRANCH_NAME }}-release"
        prerelease: true
        title: "${{ env.BRANCH_NAME }} branch"
        files: |
          ./Nog.zip
