name: Auto Delete

on: [ delete ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: |
          export REF_NAME=$(jq ".ref" $GITHUB_EVENT_PATH)
          echo "::set-env name=REF_NAME::$REF_NAME"
      - name: Delete Release
        run: |
          hub release delete $REF_NAME
      - name: Delete Tag
        run: git push -d origin "$REF_NAME-release"
