name: Auto Delete

on: [ delete ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export REF_NAME=$(jq ".ref" ${{ env.GITHUB_EVENT_PATH }})
          echo "::set-env name=REF_NAME::$REF_NAME"
      - name: Delete Release
        run: hub release delete '${{ env.REF_NAME }}'
      - name: Delete Tag
        run: git push -d origin '${{ env.REF_NAME }}-release'
