name: Auto Delete

on: [ delete ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: nelonoel/branch-name@v1
    - uses: actions/checkout@v2.3.1
    - name: Delete Release
      run: hub release show '${{ BRANCH_NAME }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
