name: Docs

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Generator api documentation
      run: cd doc-gen && cargo run && cd ..
    - name: Cleanup any leftover api docs
      run: |
        rm -rf ./book/src/api
        rm ./book/src/api_toc.md
    - name: Copy api documentation
      run: |
        cp ./doc-gen/output/api ./book/src
        cp ./doc-gen/output/SUMMARY.md ./book/src/api_toc.md
