name: Docs

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Generator api documentation
      run: cd doc-gen && cargo run && cd ..
    - name: Cleanup any leftover api docs
      run: |
        [ ! -e ./book/src/api ] || rm -rf ./book/src/api
        [ ! -e ./book/src/api_toc.md ] || rm ./book/src/api_toc.md
    - name: Copy api documentation
      run: |
        cp ./doc-gen/output/api ./book/src
        cp ./doc-gen/output/SUMMARY.md ./book/src/api_toc.md
    - name: Commit changes
      run: |
        git commit -am "[BUILD_DOCS WORKFLOW]: update docs"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
